### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by MatyasK** [patolin/rc-receiver-joystick#2]
I get this error while compiling: ( I replaced the library files according to the hack!)
`Archiving built core (caching) in: C:\Users\Matyas#\AppData\Local\Temp\arduino_cache_981071\core\core_digistump_avr_digispark-tiny_7f32ee7bd573ae43781e0347e06a677d.a
libraries\DigisparkJoystick\usbdrvasm.S.o: In function `__vector_2':

C:\Users\Matyas#\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkJoystick/usbdrvasm165.inc:41: multiple definition of `__vector_2'

libraries\DigisparkTinyPinChange\TinyPinChange.cpp.o:C:\Users\Matyas#\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkTinyPinChange/TinyPinChange.cpp:57: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Digispark (Default - 16.5mhz).`

**Comment by patolin** [comment]
Are you sure you replaced correctly the files from the hack library? https://github.com/J-Rios/Digispark_DigiUSB-SoftSerial/tree/master/digistump/avr
 You must be sure that the avr folder is correctly replaced, because the new library has a different file structure (it includes files for SAM architecture, which is not used in the original Digispark library). I had the same error in an early stage, but checking the files location of the new library it was corrected

Also, Im using Arduino IDE 1.8.5
